### ISSUE TITLE
server : add "token healing" support

### ISSUE THREAD

**Issue by CyberShadow** [ggml-org/llama.cpp#5765]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [X] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [X] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [X] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

Hi! I am experimenting with using llama.cpp as a general-purpose code completion backend, similar to TabNine.

I am encountering a small problem: if the completion prompt ends mid-word, the results are not very accurate. For example, for a prompt such as `Five, Four, Thre` [sic], the model will often ignore the typo and suggest `, Two` (forming `Thre, Two`).

I think, as an option to the `/completion` server API, the following optional behavior would be useful:

1. Tokenize the text
2. Chop off the last token
3. Run the prediction with the remaining tokens, but only consider those tokens whose bytes start with the bytes of the last token.

Thanks!

**Comment by ilyannn** [comment]
@ggerganov I'd like to try working on it as my first issue!

**Comment by ggerganov** [comment]
Ok. This can be demonstrated in one of the examples. One way would be to add it to `main` or `simple` + extend `llama_sampling_sample` with the necessary functionality

**Comment by mare5x** [comment]
Hi @ilyannn, do you still want to work on this? I've created a draft PR (#7028) that demonstrates token healing, but I still haven't added it to `main` or `server`. We can collaborate on that, if you'd like.

**Comment by 99991** [comment]
In some cases, constraining prefix tokens with a GBNF grammar might be an acceptable workaround: https://github.com/ggerganov/llama.cpp/issues/11536#issuecomment-2643444612

**Comment by lee101** [comment]
i did this in https://text-generator.io and added a min_probability param to help anyone out doing this form of fast autocomplete https://github.com/TextGeneratorio/text-generator.io/blob/1565ef108ac58731086acb253581aa5c644c7156/questions/text_generator_inference.py#L187 

Basically i just rewind by a token, then during generation i check to ensure, using prefix_token_allowed_fn , to ensure i only pick tokens that have the prefix of that token that i rewinded by.

Works well for autocomplete! :) 

sometimes call it the sub token splitting issue

**Comment by agent-enemy-2** [comment]
Hey all, I saw this thread went a little stale and figured I'd take this opportunity to get my feet wet with the repo. PR is here: https://github.com/ggml-org/llama.cpp/pull/19238

Apologies if I am stepping on anyones toes! Happy to not merge my PR. Was more or less just to learn the code base a bit. Fun feature though!

**Comment by binoysaha025** [comment]
Hi! I'm a student in the CodePath AI301 program and I'd like to work on this issue. I have reviewed the existing draft PR (#19238) and noticed it uses a retry-loop approach; I am planning to implement this via logit masking at sampling time instead, constraining candidates to tokens whose bytes start with the rewound prefix token, which keeps it to a single inference pass. I will start by mapping the sampling pipeline this week. 

Any pointers on the right hooks in llama_sampling_sample would be appreciated!
